'use strict';
console.log('Truth table for conjunction of 3 conditions');
console.log('var1\tvar2\tvar3\tvar1 && var2\tvar2 && var3\tvar1 && var3\tvar1 && var2 && var3');
var var1 = true;
var var2 = true;
var var3 = true;
console.log((var1 + '\t' + var2 + '\t' + var3) + '\t\t' + (var1 && var2) + '\t\t\t' + (var2 && var3) + '\t\t\t' + (var1 && var3) + '\t\t\t\t' + (var1 && var2 && var3));
var var1 = false;
var var2 = true;
var var3 = true;
console.log((var1 + '\t' + var2 + '\t' + var3) + '\t\t' + (var1 && var2) + '\t\t\t' + (var2 && var3) + '\t\t\t' + (var1 && var3) + '\t\t\t\t' + (var1 && var2 && var3));
var var1 = false;
var var2 = false;
var var3 = true;
console.log((var1 + '\t' + var2 + '\t' + var3) + '\t\t' + (var1 && var2) + '\t\t\t' + (var2 && var3) + '\t\t\t' + (var1 && var3) + '\t\t\t\t' + (var1 && var2 && var3));
var var1 = false;
var var2 = true;
var var3 = false;
console.log((var1 + '\t' + var2 + '\t' + var3) + '\t\t' + (var1 && var2) + '\t\t\t' + (var2 && var3) + '\t\t\t' + (var1 && var3) + '\t\t\t\t' + (var1 && var2 && var3));
var var1 = true;
var var2 = true;
var var3 = false;
console.log((var1 + '\t' + var2 + '\t' + var3) + '\t\t' + (var1 && var2) + '\t\t\t' + (var2 && var3) + '\t\t\t' + (var1 && var3) + '\t\t\t\t' + (var1 && var2 && var3));
var var1 = true;
var var2 = false;
var var3 = true;
console.log((var1 + '\t' + var2 + '\t' + var3) + '\t\t' + (var1 && var2) + '\t\t\t' + (var2 && var3) + '\t\t\t' + (var1 && var3) + '\t\t\t\t' + (var1 && var2 && var3));
var var1 = true;
var var2 = false;
var var3 = false;
console.log((var1 + '\t' + var2 + '\t' + var3) + '\t\t' + (var1 && var2) + '\t\t\t' + (var2 && var3) + '\t\t\t' + (var1 && var3) + '\t\t\t\t' + (var1 && var2 && var3));
var var1 = false;
var var2 = false;
var var3 = false;
console.log((var1 + '\t' + var2 + '\t' + var3) + '\t\t' + (var1 && var2) + '\t\t\t' + (var2 && var3) + '\t\t\t' + (var1 && var3) + '\t\t\t\t' + (var1 && var2 && var3));
